name: Publish web

on:
  repository_dispatch:
  push:
    branches:
      - master
  workflow_dispatch:

defaults:
  run:
    working-directory: Covid19Observer.Web
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm i
    - run: npm run build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Covid19Observer.Web/dist
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: heroku-express
        FOLDER: Covid19Observer.Express
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
